version: '3.8'

# Local development configuration
services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    image: python-s3-webapp-backend:local
    ports:
      - "5001:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - PROVIDER=${PROVIDER:-gemini}
      - MODEL=${MODEL:-gemini-1.5-flash}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend/src:/app/src:ro  # Mount source for development
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5001
    image: python-s3-webapp-frontend:local
    ports:
      - "3000:80"  # Changed to 3000 for development
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped